// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using luna.Models;

namespace luna.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("luna.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Product");

                    b.HasKey("id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("luna.Models.Product", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Categoria");

                    b.Property<int>("Descripcion");

                    b.Property<int>("Precio");

                    b.Property<string>("Title");

                    b.HasKey("ProductoId");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
